### PR TITLE
Push forward the library

### PR DESCRIPTION
**Pull request by toomuchdesign**
As mentioned in #5, here is an initial PR to update the library and make it shine.

Happy to discuss about it and to add additional points.

### Generic setup
- [x] declare proper peerDependencies
- [x] update RollupJS configuration to not bundle external libraries
- [x] remove `dist` folder from version control
- [x] setup FlowJS
- [ ] revamp docs
- [x] GitHub's PR's / issues templates
- [x] auto format code with `prettier` on pre-commit?
- [x] add [all-contributors](https://github.com/kentcdodds/all-contributors) table to the bottom of the docs

### Component specific
- [x] provide `tabIndex` and `role` as props
- [ ] add [Coveralls](https://coveralls.io/) integration
- [ ] add Travis integration
- [ ] add Coveralls and Travis badge to docs
- [x] `ariaLabel` & `className` `undefined` by default
- [x] provide support to both`onClick` and `onMouseDown` events
- [x] fix `StopPropagation`'s `onKeyDown` method (`e` vs. `event`)
- [ ] since they are stateless, rewrite both component as a pure functions

## Under evaluation
- set up a demo?
- ..anything else?

### CODE REVIEW

**Comment by MiroDojkic** [comment]
This is looking good!
Would you like this to be merged before working on any other items from todo list, so that it's not all in one big PR?

#### Regarding under evaluation:
- We could also just setup ESLint with prettier to check format on new commit and let devs format the code? I think either way is good.
- Adding contributors list makes sense, will have to catch up with the linked specs though 🙂
- Sure, I will look to take some time through next week to setup demos on [Stackblitz](http://stackblitz.com/) for use case with and without `StopPropagation` component.

Thank you for the great work! 🍻

**Comment by toomuchdesign** [comment]
My pleasure @MiroDojkic !
I'd prefer to work on this branch for a little while in order to still be able to rebase something just in case. It won't take long!

I'll work on the first 2 points in the next days and leave the demo to you! 😃 

As soon as we merge this PR we'll be also able to connect the repo to Coveralls and Travis, the configuration should be already there.

So, have an awesome weekend, we'll catch up soon! 🍻

**Comment by toomuchdesign** [comment]
From my side, we're ready to merge.
👍

**Review by MiroDojkic — APPROVED** [review]
Awesome work!

**Comment by toomuchdesign** [comment]
Hi @MiroDojkic, do you any help to on the last point in order to be ready to publish?
Cheers!

**Comment by MiroDojkic** [comment]
Hi @toomuchdesign, work caught up with me so I got a bit distracted.
I'll wrap up the demo this weekend and publish the new version.

**Comment by toomuchdesign** [comment]
No worries! Let me know if you need help. Ciao!

**Pull request merged**
